<template>
	<view class="home">
		<nav-bar :title="title" :color="color" :backgroundColor="backgroundColor">
		</nav-bar>
		<view class="home-search">
			<view class="search">
				<text class="iconfont iconsearch">	
				</text>{{searchName}}
			</view>
		</view>
		<view class="home-content">
			<block v-for="(item,index) in filmsList" :key="index">
				<list-part :title="item.title" :subjects="item.subjects"></list-part>
			</block>
		</view>
	</view>
</template>

<script>
	import listPart from "../../components/listPart/listPart.vue"
	import pic from "../../static/image/ad/default.webp"
	import navBar from "../../components/navBar/navBar.vue" 
	
	export default {
		data() {
			return {
				searchName: '搜索',
				title:"首页",
				color:"#fff",
				backgroundColor:"#41B955",
				filmsList:[
					{
						title:"正在热映",
						subjects:[
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							}
						]
					}
				,
				{
						title:"即将上映",
						subjects:[
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							},
							{
								rating:{
									average:7.7
								},
								genres:["剧情","犯罪","悬疑"],
								title:"大赢家",
								casts:[
									{
										avatars:{
											small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
											medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
										},
										name_en:"Yang Xiao",
										name:"肖央",
										alt:"https://movie.douban.com/celebrity/1274979/",
										id:"1274979"
									}
								],
								durations:["112分钟"],
								collect_count:23,
								mainland_pubdate:"2020-02-21",
								has_video:false,
								original_title:"大赢家",
								subtype:"movie",
								directors:[
									{
										avatars:{
											small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
											medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
										},
										name_en:"Boon-lip Quah",
										name:"柯汶利",
										alt:"https://movie.douban.com/celebrity/1417306/",
										id:"1417306"
									}
								],
								pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
								year:2020,
								images:{
									small:pic,
									large:pic,
									medium:pic,
								},
								id:"23"
								
							}
						]
					},
					{
							title:"top250",
							subjects:[
								{
									rating:{
										average:7.7
									},
									genres:["剧情","犯罪","悬疑"],
									title:"大赢家",
									casts:[
										{
											avatars:{
												small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
											},
											name_en:"Yang Xiao",
											name:"肖央",
											alt:"https://movie.douban.com/celebrity/1274979/",
											id:"1274979"
										}
									],
									durations:["112分钟"],
									collect_count:23,
									mainland_pubdate:"2020-02-21",
									has_video:false,
									original_title:"大赢家",
									subtype:"movie",
									directors:[
										{
											avatars:{
												small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
											},
											name_en:"Boon-lip Quah",
											name:"柯汶利",
											alt:"https://movie.douban.com/celebrity/1417306/",
											id:"1417306"
										}
									],
									pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
									year:2020,
									images:{
										small:pic,
										large:pic,
										medium:pic,
									},
									id:"23"
									
								},
								{
									rating:{
										average:7.7
									},
									genres:["剧情","犯罪","悬疑"],
									title:"大赢家",
									casts:[
										{
											avatars:{
												small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
											},
											name_en:"Yang Xiao",
											name:"肖央",
											alt:"https://movie.douban.com/celebrity/1274979/",
											id:"1274979"
										}
									],
									durations:["112分钟"],
									collect_count:23,
									mainland_pubdate:"2020-02-21",
									has_video:false,
									original_title:"大赢家",
									subtype:"movie",
									directors:[
										{
											avatars:{
												small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
											},
											name_en:"Boon-lip Quah",
											name:"柯汶利",
											alt:"https://movie.douban.com/celebrity/1417306/",
											id:"1417306"
										}
									],
									pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
									year:2020,
									images:{
										small:pic,
										large:pic,
										medium:pic,
									},
									id:"23"
									
								},
								{
									rating:{
										average:7.7
									},
									genres:["剧情","犯罪","悬疑"],
									title:"大赢家",
									casts:[
										{
											avatars:{
												small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
											},
											name_en:"Yang Xiao",
											name:"肖央",
											alt:"https://movie.douban.com/celebrity/1274979/",
											id:"1274979"
										}
									],
									durations:["112分钟"],
									collect_count:23,
									mainland_pubdate:"2020-02-21",
									has_video:false,
									original_title:"大赢家",
									subtype:"movie",
									directors:[
										{
											avatars:{
												small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
											},
											name_en:"Boon-lip Quah",
											name:"柯汶利",
											alt:"https://movie.douban.com/celebrity/1417306/",
											id:"1417306"
										}
									],
									pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
									year:2020,
									images:{
										small:pic,
										large:pic,
										medium:pic,
									},
									id:"23"
									
								},
								{
									rating:{
										average:7.7
									},
									genres:["剧情","犯罪","悬疑"],
									title:"大赢家",
									casts:[
										{
											avatars:{
												small:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												large:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp",
												medium:"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1518431956.11.webp"
											},
											name_en:"Yang Xiao",
											name:"肖央",
											alt:"https://movie.douban.com/celebrity/1274979/",
											id:"1274979"
										}
									],
									durations:["112分钟"],
									collect_count:23,
									mainland_pubdate:"2020-02-21",
									has_video:false,
									original_title:"大赢家",
									subtype:"movie",
									directors:[
										{
											avatars:{
												small:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												large:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp",
												medium:"https://img9.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1559275231.36.webp"
											},
											name_en:"Boon-lip Quah",
											name:"柯汶利",
											alt:"https://movie.douban.com/celebrity/1417306/",
											id:"1417306"
										}
									],
									pubdates:["201912-07(大规模点映)","2019-12-13(中国大陆)"],
									year:2020,
									images:{
										small:pic,
										large:pic,
										medium:pic,
									},
									id:"23"
									
								}
							]
						}
				]
			}
		},
		components:{
			listPart,
			navBar
		},
		onLoad() {
			this.getInTheaters()
		},
		methods: {
			//获取正在上映的电影数据
			getInTheaters(){
				this.$store.dispatch("getInTheatersData")
			}
		}
	}
</script>
 
<style lang="less" scoped>
	.home-search{
		display:flex;
		justify-content:center;
		align-items:center;
		height:90upx;
		background-color:#41B955;
		.search{
			height:68upx;
			background-color:#ffffff;
			width:90%;
			border-radius:8upx;
			display:flex;
			justify-content:center;
			align-items:center;
			color:#C0C0C0;
			font-size:24upx;
		}
	}
	
</style>
