const {saveData} =require('../utils/localData.js') 
module.exports={
	//城市名
	GET_CITY_NAME_BY_GEOHASH(state,city){
		if(city.includes('市')){
			city=city.replace(/[市]$/gi,"")
		}
		saveData('city',city)
		state.localCity=city
	},
	//正在上映
	GET_IN_THEATERS_DATA(state,{...data}){
		state.inTheaters=data
	},
	//即将上映
	GET_COMING_SOON_FILES_DATA(state,{...data}){
		state.oComingSoon=data
	},
	//top250
	GET_TOP250_FILES_DATA(state,{...data}){
		state.oTop250=data 
	},
	//新片榜
	GET_NEW_MOVIES_DATA(state,{...data}){
		state.oNewMovies=data 
	},
	//口碑榜
	GET_WEEKLY_DATA(state,{...data}){
		state.oWeekly=data
	},
	//北美票房榜
	GET_US_BOX_MOVIES_DATA(state,{...data}){
		state.oUsBox=data
	}
	
}